// This file is auto-generated by generate_polyfill_header.sh. DO NOT EDIT.
#import <Foundation/Foundation.h>

static NSString *scriptsPost = @"console.log('Start Polyfills-Post');\
const styleId=\"%@\";let styleSheet=document.getElementById(styleId);if(!styleSheet){styleSheet=document.createElement(\"style\");styleSheet.type=\"text/css\";styleSheet.innerText=`body, html { max-width: 100%; overflow-x: hidden; }`;styleSheet.id=styleId;document.head.appendChild(styleSheet)}";
